name: Build

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: Setup Android build environment
        uses: android-actions/setup-android@v2
      - name: Build whole project with gradle
        run: ./gradlew build
